package swat_cat.com.imagefetcher.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "IMAGE".
 */
public class Image {

    private Long id;
    private String title;
    private String url;
    private String thumbUrl;
    private Integer imageHeight;
    private Integer imageWidth;
    private Integer thumbHeight;
    private Integer thumbWidth;
    private String Uri;
    private Boolean isSaved;

    public Image() {
    }

    public Image(Long id) {
        this.id = id;
    }

    public Image(Long id, String title, String url, String thumbUrl, Integer imageHeight, Integer imageWidth, Integer thumbHeight, Integer thumbWidth, String Uri, Boolean isSaved) {
        this.id = id;
        this.title = title;
        this.url = url;
        this.thumbUrl = thumbUrl;
        this.imageHeight = imageHeight;
        this.imageWidth = imageWidth;
        this.thumbHeight = thumbHeight;
        this.thumbWidth = thumbWidth;
        this.Uri = Uri;
        this.isSaved = isSaved;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getThumbUrl() {
        return thumbUrl;
    }

    public void setThumbUrl(String thumbUrl) {
        this.thumbUrl = thumbUrl;
    }

    public Integer getImageHeight() {
        return imageHeight;
    }

    public void setImageHeight(Integer imageHeight) {
        this.imageHeight = imageHeight;
    }

    public Integer getImageWidth() {
        return imageWidth;
    }

    public void setImageWidth(Integer imageWidth) {
        this.imageWidth = imageWidth;
    }

    public Integer getThumbHeight() {
        return thumbHeight;
    }

    public void setThumbHeight(Integer thumbHeight) {
        this.thumbHeight = thumbHeight;
    }

    public Integer getThumbWidth() {
        return thumbWidth;
    }

    public void setThumbWidth(Integer thumbWidth) {
        this.thumbWidth = thumbWidth;
    }

    public String getUri() {
        return Uri;
    }

    public void setUri(String Uri) {
        this.Uri = Uri;
    }

    public Boolean getIsSaved() {
        return isSaved;
    }

    public void setIsSaved(Boolean isSaved) {
        this.isSaved = isSaved;
    }

}
